AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: CloudWatch Logs Error to Slack Bot Notification using SSM Parameter Store

Parameters:
  SlackBotTokenParameter:
    Type: String
    Description: "The name of the SSM Parameter that stores the Slack Bot OAuth token"

  SlackChannelIdParameter:
    Type: String
    Description: "The name of the SSM Parameter that stores the Slack channel ID"

  CloudWatchLogsLogGroupName:
    Type: String
    Description: "The name of the CloudWatch Logs Log Group to monitor for errors"

Resources:
  SlackNotificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      #Handler: src.app.lambda_handler
      CodeUri: ./src
      Handler: app.lambda_handler
      Runtime: python3.11
      MemorySize: 128
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            Effect: Allow
            Action:
              - ssm:GetParameter
              - ssm:GetParameters
            Resource: 
              - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${SlackBotTokenParameter}"
              - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${SlackChannelIdParameter}"
      Environment:
        Variables:
          SLACK_BOT_TOKEN_PARAMETER: !Ref SlackBotTokenParam
          SLACK_CHANNEL_ID_PARAMETER: !Ref SlackChannelIdParam

  LogGroupSubscriptionFilter:
    Type: AWS::Logs::SubscriptionFilter
    Properties:
      LogGroupName: !Sub "${CloudWatchLogsLogGroupName}"
      # Error/ERROR にマッチするログをフィルタリング
      FilterPattern: ?ERROR ?Error ?error
      DestinationArn: !GetAtt SlackNotificationFunction.Arn

  LambdaInvokePermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName: !GetAtt SlackNotificationFunction.Arn
      Action: 'lambda:InvokeFunction'
      Principal: 'logs.amazonaws.com'
      SourceArn: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:${CloudWatchLogsLogGroupName}:*"
      SourceAccount: !Ref 'AWS::AccountId'

Outputs:
  SlackNotificationFunctionArn:
    Description: "ARN of the Lambda function that sends notifications to Slack"
    Value: !GetAtt SlackNotificationFunction.Arn
